baseURL = "https://gordon-landreth-photography.arts-link.com"
copyright = "© 2024 Gordon Landreth Photography"
defaultContentLanguage = "en"
# disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Los_Angeles"
timeout = "120s"
title = ""
private = true

[params]
  defaultTheme = "dark"
  description = "The photo albums of Gordon Landreth's life."
  title = "Gordon Landreth Photography"
  [params.author]
    email = "ben@benstrawbridge.com"
    name = "Ben Strawbridge"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    github = "https://github.com/arts-link/gordon-landreth-photography/"
    #youtube = "https://www.youtube.com/"
    #email = "mailto:ben@benstrawbridge.com"
    #website = "https://www.benstrawbridge.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
  [params.gallerydeluxe.watermark]
    image = "images/benstraw.png" # relative to /assets
    posx  = "right"                    # one of "left", "center", "right"
    posy  = "bottom"                  # one of "top", "center", "bottom"
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "Website by arts-link.com"
    url = "https://www.arts-link.com/?utm_source=gordon-landreth-photography&utm_medium=footer&utm_campaign=website"
    weight = 3


[services]
  [services.rss]
    limit = 100


